In [2]:
import os 
from os.path import join,abspath
import scipy.io as sio
import numpy as np

from utils.get_feedback_blocks import get_feedback_blocks
from utils.get_response_onsets import get_response_onsets
from utils.get_log_vectors import get_log_vectors


In [2]:
log_dir      = "/home/rantanplan/Documents/Paris/HEART_PPI/heart_logs/"
mat_dir      = "/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/"
onset_dir    = "/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/RESPONSE/"
feedback_dir = "/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/FEEDBACK/"

mapping = dict(GS248="sub_01",
               CM249="sub_02",
               WT250="sub_03",
               #XA251="sub_04", excluded from analysis
               #GS252="sub_05", excluded from analysis
               LT253="sub_06",
               MU254="sub_07",
               CG255="sub_08",
               PJ256="sub_09",
               EM257="sub_10",
               YJ258="sub_11",
               #GA259="sub_12", excluded from analysis
               AF260="sub_13",
               MT261="sub_14",
               CL262="sub_15",
               CG263="sub_16",
               TW265="sub_17",
               BP267="sub_18",
               CS268="sub_19",
               TC269="sub_20")


In [3]:
### Loop through folder with mat files and extract onsets and durations for each of the two
### feedback conditions (Synchronous / Asynchronous)

for root, dirs, files in os.walk(mat_dir):
    for name in files:
        mat = join(root, name)

        if mat.endswith(".mat"):
            mat_file = sio.loadmat(mat)

            if "task_type" in mat_file.keys():
                if 'MINEOTHER' in mat_file["task_type"]:

                    blocks = get_feedback_blocks(mat)
                    print(blocks["name"])
                    print(blocks["sync_onset"], "----- Len: {}".format(len(blocks["sync_onset"])))
                    print(blocks["sync_duration"],"----- Len: {}".format(len(blocks["sync_duration"])))
                    print(blocks["async_onset"],"----- Len: {}".format(len(blocks["async_onset"])))
                    print(blocks["async_duration"],"----- Len: {}".format(len(blocks["async_duration"])))
                    output_name = join(feedback_dir, mapping[mat[-9:-7]+mat[-12:-9]]+ "_feedback.mat")
                    print(output_name+ "\n")
                    sio.savemat(output_name,{"feedback":blocks})

263CG
[  8  79 112 157 195 226 281 314 365] ----- Len: 9
[23 17 13 36 14 17 16 33 13] ----- Len: 9
[ 32  47  63  97 126 139 210 244 298 348 380] ----- Len: 11
[13 14 15 14 11 17 15 36 15 16 31] ----- Len: 11
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/FEEDBACK/sub_16_feedback.mat

250WT
[  5 175 207 304 352 400] ----- Len: 6
[21 18 20 23 19 32] ----- Len: 6
[ 28  73  96 112 229 251 276 330 373 434 462 495 533] ----- Len: 13
[43 20 14 61 20 23 17 20 25 25 31 36  1] ----- Len: 13
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/FEEDBACK/sub_03_feedback.mat

258YJ
[ 63 112 136 160 206 223 370 443 495] ----- Len: 9
[21 22 22 25 15 17 45 23 55] ----- Len: 9
[ 25 187 241 291 352 416 478] ----- Len: 7
[36 18 48 17 17 26 16] ----- Len: 7
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/FEEDBACK/sub_11_feedback.mat

249CM
[  9  28  84 132 180 198 287 328 375 416 460 495] ----- Len: 12
[17 12 14 22 15 21 22 23 21 42 31 19] ----- Len: 12
[ 42 100 156 220 239 310 353 3

In [4]:
for root, dirs, files in os.walk(mat_dir):
    for name in files:
        mat = join(root, name)

        if mat.endswith(".mat"):
            mat_file = sio.loadmat(mat)
            
            if "task_type" in mat_file.keys():
                if 'MINEOTHER' in mat_file["task_type"]:

                    onsets = get_response_onsets(mat)
                    print(onsets["name"])
                    print(onsets["mine_onsets"])
                    print(onsets["other_onsets"])
          
                    output_name = join(onset_dir, mapping[mat[-9:-7]+mat[-12:-9]]+ "_responses.mat")
                    print(output_name+ "\n")
                    sio.savemat(output_name,{"responses":onsets})

263CG
[ 31  45  61  96 125 137 193 209 243 313 364 378 411]
[ 78 111 156 225 280 297 347]
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/RESPONSE/sub_16_responses.mat

250WT
[ 26 110 173 227 249 274 293 327 350 371 432 493]
[ 71  93 193 398 459 531 534]
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/RESPONSE/sub_03_responses.mat

258YJ
[ 61  84 134 158 185 221 240 308 369 415 466]
[205 289 442 494 550]
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/RESPONSE/sub_11_responses.mat

249CM
[ 40  83  98 154 195 219 237 309 351 396 415 458 514]
[ 26 122 178 264 326 373 491]
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/RESPONSE/sub_02_responses.mat

267BP
[ 79  98 154 176 225 255 294 315 345 358 452 457]
[ 50  66 114 134 195 332 395 413]
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vectors/RESPONSE/sub_18_responses.mat

262CL
[ 19  31  70 102 119 161 181 219 290 317]
[ 48 204 233 262 301 343 351]
/home/rantanplan/Documents/Paris/HEART_PPI/heart_vec

In [ ]:
for root, dirs, files in os.walk(log_dir):
    for name in files:
        log = join(root, name)
        
        if log.endswith("log"):
            if log[-12:-7] in mapping.keys():
                output_name = join(log_dir, mapping[log[-12:-7]]+ "_vectors.mat")
                vectors = get_log_vectors(log)
                sio.savemat(output_name,{"vectors":vectors})